### ISSUE TITLE
NPE when using GWT SDK 2.8.0.beta1

### ISSUE THREAD

**Issue by TDesjardins** [gwt-plugins/gwt-eclipse-plugin#138]
When using GWT SDK 2.8.0.beta1 the following error message appears in the Error Log:

Could not compare '2.8.0.beta1' to '2.8.0.beta1', ignoring this version

Stacktrace:

`java.lang.NumberFormatException: For input string: "beta1"
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.google.gdt.eclipse.core.sdk.SdkUtils.parseVersionComponent(SdkUtils.java:250)
	at com.google.gdt.eclipse.core.sdk.SdkUtils.compareVersionStrings(SdkUtils.java:160)
	at com.google.gdt.eclipse.core.sdk.SdkUtils$MaxSdkVersionComputer.computeMaxSdkVersion(SdkUtils.java:57)
	at com.google.gdt.eclipse.suite.ext.GdtExtPlugin$2.checkSiteXMLForUpdates(GdtExtPlugin.java:207)
	at com.google.gdt.eclipse.core.update.internal.core.FeatureUpdateChecker.checkForUpdates(FeatureUpdateChecker.java:242)
	at com.google.gdt.eclipse.suite.ext.update.CompositeArtifactsDowloadJobChangeListener$2.done(CompositeArtifactsDowloadJobChangeListener.java:251)
	at org.eclipse.core.internal.jobs.JobListeners$3.notify(JobListeners.java:42)
	at org.eclipse.core.internal.jobs.JobListeners.doNotify(JobListeners.java:113)
	at org.eclipse.core.internal.jobs.JobListeners.done(JobListeners.java:151)
	at org.eclipse.core.internal.jobs.JobManager.endJob(JobManager.java:694)
	at org.eclipse.core.internal.jobs.WorkerPool.endJob(WorkerPool.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:72)`

The reason for this is, that 'beta' is not a valid version suffix. Method 'parseVersionComponent()' in class 'com.google.gdt.eclipse.core.sdk.SdkUtils' only supports 'rc' and 'ms'.

See: [Code](https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/1ef5a70bf6a1dabbdb6fd327a4750c1468e0227d/plugins/com.google.gdt.eclipse.core/src/com/google/gdt/eclipse/core/sdk/SdkUtils.java#L247)

**Comment by branflake2267** [comment]
I know what you're referring too. I've marked this a high priority fix. I'll aim to work on this sometime this week.

**Comment by branflake2267** [comment]
RC1 is out and beta1 is old. I'm going to close this.

**Comment by TDesjardins** [comment]
Hello Brandon,

do you think this is the last beta version of a GWT SDK? When the next beta will be out, we will get the same error. Maybe it is not worth to support beta versions in the plugin because this is a rarely use case. If so, then this is a reason to close this. If not we should reopen the issue.

**Comment by branflake2267** [comment]
Well, there is a possibility of that.

**Comment by branflake2267** [comment]
I have added beta to the SdkUtils.

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/158

**Comment by branflake2267** [comment]
I'll close it now that beta has been added. Thanks for reporting.

**Comment by TDesjardins** [comment]
Thanks Brandon.
