### ISSUE TITLE
Crash in gwt-eclipse-plugin If a GWT_HOME ends in a -xxx where "xxx" is not numeric

### ISSUE THREAD

**Issue by DALDEI** [gwt-plugins/gwt-eclipse-plugin#169]
Eclipse Neon 
Version: Neon Release (4.6.0)
Build id: 20160613-1800
Gwt Plug 3.9.4.v20160706

Install gwt-2.7 to /Java
Symlink to gwt-latest 
 `   ln -s /Java/gwt-2.7 /Java/gwt-latest
`
Set GWT_HOME to /Java/gwt-latest  
`   export GWT_HOME=/Java/gwt-latest
`
Import a gradle project (gradle buildship) which includes the gwt plugin.
   apply plugin: 'gwt'

On import when the first gwt project is found it crashes with a stacktrace and refuses to load the project or any more.

------------- 

!SESSION 2016-09-09 21:30:51.420 -----------------------------------------------
eclipse.buildId=4.6.0.I20160606-1100
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:31:58.401
!MESSAGE Starting the AWS toolkit core plugin...

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.096
!MESSAGE No profile found: default

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.100
!MESSAGE No profile found: local

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.100
!MESSAGE No profile found: marklogic

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.100
!MESSAGE No profile found: marklogicw

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.101
!MESSAGE No profile found: nexstra

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.101
!MESSAGE No profile found: nexstraw

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.102
!MESSAGE No profile found: dei

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.102
!MESSAGE No profile found: calldei

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.102
!MESSAGE No profile found: xmlsh

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.103
!MESSAGE No profile found: nas

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.103
!MESSAGE No profile found: pge

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.103
!MESSAGE No profile found: marklogic-telemetry

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.125
!MESSAGE Monitoring content of /home/dlee/.aws/credentials

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.211
!MESSAGE AWS toolkit core plugin initialized after 2813 milliseconds.

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.222
!MESSAGE The current accountId is not found in the system. Switching to the default account.

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:32:01.547
!MESSAGE Initialized a new Cognito identity us-east-1:6e284c3e-6349-400b-b974-09340a836817
!SESSION 2016-09-09 21:38:25.226 -----------------------------------------------
eclipse.buildId=4.6.0.I20160606-1100
java.version=1.8.0_101
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:39:17.170
!MESSAGE Starting the AWS toolkit core plugin...

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:39:19.230
!MESSAGE Monitoring content of /home/dlee/.aws/credentials

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:39:19.378
!MESSAGE AWS toolkit core plugin initialized after 2209 milliseconds.

!ENTRY com.amazonaws.eclipse.core 1 0 2016-09-09 21:39:19.390
!MESSAGE Found valid identity id cache us-east-1:6e284c3e-6349-400b-b974-09340a836817

!ENTRY com.google.gwt.eclipse.core 1 0 2016-09-09 22:17:55.000
!MESSAGE Reset default editor for extension: xml

!ENTRY org.eclipse.buildship.core 4 0 2016-09-09 22:17:56.130
!MESSAGE Synchronize Gradle builds with workspace failed due to an unexpected error.
!STACK 0
java.lang.NumberFormatException: For input string: "latest"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.google.gdt.eclipse.core.sdk.SdkUtils.parseVersionComponent(SdkUtils.java:250)
	at com.google.gdt.eclipse.core.sdk.SdkUtils.compareVersionStrings(SdkUtils.java:160)
	at com.google.gwt.eclipse.core.util.GwtVersionUtil.isGwtVersionKnownAndAtLeast25(GwtVersionUtil.java:32)
	at com.google.gwt.eclipse.core.runtime.GWTJarsRuntime.validate(GWTJarsRuntime.java:139)
	at com.google.gdt.eclipse.core.sdk.SdkClasspathContainerInitializer.getDescription(SdkClasspathContainerInitializer.java:48)
	at com.google.gwt.eclipse.core.runtime.GWTRuntimeContainerInitializer.getDescription(GWTRuntimeContainerInitializer.java:37)
	at org.eclipse.jdt.internal.core.JavaModelManager.initializeContainer(JavaModelManager.java:2935)
	at org.eclipse.jdt.internal.core.JavaModelManager.getClasspathContainer(JavaModelManager.java:1970)
	at org.eclipse.jdt.core.JavaCore.getClasspathContainer(JavaCore.java:3424)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2693)
	at org.eclipse.jdt.internal.core.JavaProject.resolveClasspath(JavaProject.java:2616)
	at org.eclipse.jdt.internal.core.ClasspathEntry.validateClasspath(ClasspathEntry.java:1772)
	at org.eclipse.jdt.internal.core.SetClasspathOperation.verify(SetClasspathOperation.java:118)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:784)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3097)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3059)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3112)
	at org.eclipse.buildship.core.workspace.internal.ClasspathContainerUpdater.updateClasspathContainerEntries(ClasspathContainerUpdater.java:156)
	at org.eclipse.buildship.core.workspace.internal.ClasspathContainerUpdater.updateProjectClasspath(ClasspathContainerUpdater.java:134)
	at org.eclipse.buildship.core.workspace.internal.ClasspathContainerUpdater.updateContainers(ClasspathContainerUpdater.java:91)
	at org.eclipse.buildship.core.workspace.internal.ClasspathContainerUpdater.update(ClasspathContainerUpdater.java:168)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenJavaProject(SynchronizeGradleBuildOperation.java:225)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenWorkspaceProject(SynchronizeGradleBuildOperation.java:213)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.addNewEclipseProjectToWorkspace(SynchronizeGradleBuildOperation.java:266)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeNonWorkspaceProject(SynchronizeGradleBuildOperation.java:243)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:179)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleBuildWithWorkspace(SynchronizeGradleBuildOperation.java:141)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:106)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:123)
	at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5521)
	at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5478)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:120)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:79)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:69)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

!ENTRY com.google.gdt.eclipse.core 4 0 2016-09-09 23:01:29.923
!MESSAGE Error while tracking project-level changes from a change in R/
!STACK 1
Java Model Exception: Java Model Status [Unbound classpath container: 'GWT SDK [invalid]' in project 'admin']
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2009)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.isResourceInAnOutputPath(ProjectChangeTimestampTracker.java:121)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.visitDelta(ProjectChangeTimestampTracker.java:162)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.visitDelta(ProjectChangeTimestampTracker.java:169)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.resourceChanged(ProjectChangeTimestampTracker.java:181)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.resources.ContentDescriptionManager$FlushJob.runInWorkspace(ContentDescriptionManager.java:79)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 963 2016-09-09 23:01:29.924
!MESSAGE Unbound classpath container: 'GWT SDK [invalid]' in project 'admin'

!ENTRY com.google.gdt.eclipse.core 4 0 2016-09-09 23:01:31.997
!MESSAGE Error while tracking project-level changes from a change in R/
!STACK 1
Java Model Exception: Java Model Status [Unbound classpath container: 'GWT SDK [invalid]' in project 'emca']
	at org.eclipse.jdt.internal.core.JavaProject.getResolvedClasspath(JavaProject.java:2009)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.isResourceInAnOutputPath(ProjectChangeTimestampTracker.java:121)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.visitDelta(ProjectChangeTimestampTracker.java:162)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.visitDelta(ProjectChangeTimestampTracker.java:169)
	at com.google.gdt.eclipse.core.projects.ProjectChangeTimestampTracker.resourceChanged(ProjectChangeTimestampTracker.java:181)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.broadcastChanges(NotificationManager.java:152)
	at org.eclipse.core.internal.resources.Workspace.broadcastPostChange(Workspace.java:374)
	at org.eclipse.core.internal.resources.Workspace.endOperation(Workspace.java:1469)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:46)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
!SUBENTRY 1 org.eclipse.jdt.core 4 963 2016-09-09 23:01:31.997
!MESSAGE Unbound classpath container: 'GWT SDK [invalid]' in project 'emca'

**Comment by DALDEI** [comment]
I belive it was a coincidence that GWT_HOME was set.  The crash still occurs until I found the GWT SDK setting in the Google properties.  At first the settings would not expand so I couldnt see it.

**Comment by branflake2267** [comment]
Thanks for reporting. This won't be an issue in the new version.
