### ISSUE TITLE
Exception thrown after remove and upgrade to V3

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#247]
Selecting the GWT facet in the project menu threw an error. 
```
The following will be send to: Eclipse


REPORT

anonymousId         7689a93d-d258-431c-b536-d31ae368c2c5
name                Brandon Donnelson
email               branflake2267@gmail.com
comment             
eclipseBuildId      4.6.1.M20160907-1200
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0-ea-b123
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.11.6
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            org.eclipse.jface
pluginVersion       3.12.0.v20160518-1929
code                2
severity            4
message             Problems occurred when invoking code from plug-in: "org.eclipse.jface".
fingerprint         7e516a8653391c07c831653dfa754752

Exception:java.lang.NoSuchMethodError: com.google.gwt.eclipse.core.properties.GWTProjectProperties.getFacetSyncCodeServer(Lorg/eclipse/core/resources/IProject;)Ljava/lang/Boolean;
	 at com.google.gwt.eclipse.wtp.properties.ui.GWTFacetProjectPropertyPage.loadSettings(GWTFacetProjectPropertyPage.java:53)
	 at com.google.gwt.eclipse.wtp.properties.ui.GWTFacetProjectPropertyPage.createContents(GWTFacetProjectPropertyPage.java:47)
	 at org.eclipse.jface.preference.PreferencePage.createControl(PreferencePage.java:241)
	 at org.eclipse.jface.preference.PreferenceDialog.createPageControl(PreferenceDialog.java:1430)
	 at org.eclipse.jface.preference.PreferenceDialog$9.run(PreferenceDialog.java:1197)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	 at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	 at org.eclipse.jface.preference.PreferenceDialog.showPage(PreferenceDialog.java:1189)
	 at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.showPage(FilteredPreferenceDialog.java:608)
	 at org.eclipse.jface.preference.PreferenceDialog$5.lambda$0(PreferenceDialog.java:656)
	 at org.eclipse.jface.preference.PreferenceDialog$5$$Lambda$83/339903015.run(null:-1)
	 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	 at org.eclipse.jface.preference.PreferenceDialog$5.selectionChanged(PreferenceDialog.java:653)
	 at org.eclipse.jface.viewers.StructuredViewer$3.run(StructuredViewer.java:878)
	 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	 at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	 at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	 at org.eclipse.jface.viewers.StructuredViewer.firePostSelectionChanged(StructuredViewer.java:875)
	 at org.eclipse.jface.viewers.StructuredViewer.handlePostSelect(StructuredViewer.java:1244)
	 at org.eclipse.jface.viewers.StructuredViewer$5.widgetSelected(StructuredViewer.java:1270)
	 at org.eclipse.jface.util.OpenStrategy.firePostSelectionEvent(OpenStrategy.java:265)
	 at org.eclipse.jface.util.OpenStrategy.access$5(OpenStrategy.java:259)
	 at org.eclipse.jface.util.OpenStrategy$1.lambda$1(OpenStrategy.java:431)
	 at org.eclipse.jface.util.OpenStrategy$1$$Lambda$68/974663343.run(null:-1)
	 at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
	 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:182)
	 at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4024)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3700)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	 at org.eclipse.jface.window.Window.open(Window.java:794)
	 at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:157)
	 at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	 at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	 at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:397)
	 at org.eclipse.jface.action.ActionContributionItem$$Lambda$36/923687865.handleEvent(null:-1)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4248)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1501)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1524)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1509)
	 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1313)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4072)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3698)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:483)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1519)


BUNDLES

name                org.eclipse.core.databinding.observable
version             1.6.0.v20160511-1747

name                org.eclipse.core.databinding
version             1.6.0.v20160412-0910

name                org.eclipse.core.runtime
version             3.12.0.v20160606-1342

name                org.eclipse.e4.ui.workbench
version             1.4.0.v20160517-1624

name                org.eclipse.e4.ui.workbench.swt
version             0.14.1.v20160829-0832

name                org.eclipse.equinox.app
version             1.3.400.v20150715-1528

name                org.eclipse.equinox.launcher
version             1.3.200.v20160318-1642

name                org.eclipse.jface
version             3.12.0.v20160518-1929

name                org.eclipse.swt
version             3.105.1.v20160907-0248

name                org.eclipse.ui
version             3.108.0.v20160518-1929

name                org.eclipse.ui.ide.application
version             1.1.101.v20160829-0827

name                org.eclipse.ui.ide
version             3.12.1.v20160823-0925


Extended Classpath Analysis                                 

The problematic package ‘com.google.gwt.eclipse.core.properties’ may originate in the following bundles:
com.gwtplugins.gwt.eclipse.core 0.0.0.201610051535, imported by:
    no bundle referenced on the stack trace.


```

**Comment by branflake2267** [comment]
It might have been a result of this exception. It was looking for a facet that wasn't there anymore. 

```
The following will be send to: Eclipse


REPORT

anonymousId         7689a93d-d258-431c-b536-d31ae368c2c5
name                Brandon Donnelson
email               branflake2267@gmail.com
comment             
eclipseBuildId      4.6.1.M20160907-1200
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0-ea-b123
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.11.6
osgiArch            x86_64
severity            UNKNOWN


STATUS

pluginId            org.eclipse.m2e.core
pluginVersion       1.7.0.20160603-1933
code                0
severity            4
message             Could not update project MyGxtProject40 configuration
fingerprint         7d2928d79a4cb42ab22bfebfd7398cf0

Exception:java.lang.IllegalArgumentException: Project facet com.google.gwt.facet has not been defined.
	 at org.eclipse.wst.common.project.facet.core.internal.FacetedProjectFrameworkImpl.getProjectFacet(FacetedProjectFrameworkImpl.java:234)
	 at org.eclipse.wst.common.project.facet.core.ProjectFacetsManager.getProjectFacet(ProjectFacetsManager.java:75)
	 at com.google.gwt.eclipse.wtp.maven.GwtMavenFacetManager.addGwtFacet(GwtMavenFacetManager.java:52)
	 at com.google.gwt.eclipse.wtp.maven.GwtProjectConfigurator.configure(GwtProjectConfigurator.java:50)
	 at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:501)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:494)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:432)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:345)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	 at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:342)
	 at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)


BUNDLES

name                org.eclipse.core.jobs
version             3.8.0.v20160509-0411

name                org.eclipse.core.resources
version             3.11.0.v20160503-1608

name                org.eclipse.m2e.core
version             1.7.0.20160603-1933

name                org.eclipse.m2e.core.ui
version             1.7.0.20160603-1933

name                org.eclipse.wst.common.project.facet.core
version             1.4.300.v201111030423


```

**Comment by branflake2267** [comment]
Yep, need to deal with com.google.gwt.facet.

**Comment by branflake2267** [comment]
Uninstall this: 
![screen shot 2016-10-05 at 12 35 43 pm](https://cloud.githubusercontent.com/assets/1326504/19128454/421ef480-8af8-11e6-9846-9f15c10aaf1f.png)

**Comment by branflake2267** [comment]
Re-import project. Get rid of the .settings
