### ISSUE TITLE
Plugin is constantly trying to connect to www.google-analytics.com

### ISSUE THREAD

**Issue by dnouls** [gwt-plugins/gwt-eclipse-plugin#331]
My dev machine is not allowed to be connected to the internet.
My eclipse error log is full of exceptions (every second or so) that it could not connect to the mentioned website.
Please make it a feature that we can disable the phone-home feature. I need this log to find real problems.
!ENTRY com.gwtplugins.gdt.eclipse.suite.update 4 0 2017-01-05 14:57:40.757

!MESSAGE Error trying to ping Analytics

!STACK 0

java.net.UnknownHostException: www.google-analytics.com

                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)

                at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)

                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)

                at java.net.Socket.connect(Socket.java:589)

                at java.net.Socket.connect(Socket.java:538)

                at sun.net.NetworkClient.doConnect(NetworkClient.java:180)

                at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)

                at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)

                at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)

                at sun.net.www.http.HttpClient.New(HttpClient.java:308)

                at sun.net.www.http.HttpClient.New(HttpClient.java:326)

                at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)

                at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)

                at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)

                at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)

                at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)

                at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)

                at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)

                at com.google.gdt.eclipse.suite.update.usage.AnalyticsPingManager.logPostResponse(AnalyticsPingManager.java:172)

                at com.google.gdt.eclipse.suite.update.usage.AnalyticsPingManager.sendPostRequest(AnalyticsPingManager.java:147)

                at com.google.gdt.eclipse.suite.update.usage.AnalyticsPingManager.sendPing(AnalyticsPingManager.java:107)

                at com.google.gdt.eclipse.suite.update.usage.AnalyticsPingManager.sendCompilationPing(AnalyticsPingManager.java:75)

                at com.google.gdt.eclipse.suite.update.builders.UpdateTriggerCompilationParticipant.isActive(UpdateTriggerCompilationParticipant.java:37)

                at org.eclipse.jdt.internal.core.JavaModelManager$CompilationParticipants.getCompilationParticipants(JavaModelManager.java:421)

                at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.notifyParticipants(ReconcileWorkingCopyOperation.java:239)

                at org.eclipse.jdt.internal.core.ReconcileWorkingCopyOperation.executeOperation(ReconcileWorkingCopyOperation.java:95)

                at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)

                at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:790)

                at org.eclipse.jdt.internal.core.CompilationUnit.reconcile(CompilationUnit.java:1250)

                at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:128)

                at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.access$0(JavaReconcilingStrategy.java:110)

                at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy$1.run(JavaReconcilingStrategy.java:90)

                at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)

                at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:87)

                at org.eclipse.jdt.internal.ui.text.java.JavaReconcilingStrategy.reconcile(JavaReconcilingStrategy.java:154)

                at org.eclipse.jdt.internal.ui.text.CompositeReconcilingStrategy.reconcile(CompositeReconcilingStrategy.java:89)

                at org.eclipse.jdt.internal.ui.text.JavaCompositeReconcilingStrategy.reconcile(JavaCompositeReconcilingStrategy.java:104)

                at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:73)

                at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:207)

**Comment by branflake2267** [comment]
This is fixed, although not released yet.
