### ISSUE TITLE
Eclipse 4.7.1 (oxygen.1) compatibility

### ISSUE THREAD

**Issue by axls** [gwt-plugins/gwt-eclipse-plugin#364]
`New Project Wizard` doesn't work in Eclipse 4.7.1.

Eclipse reports next error:
```
The following will be send to: Eclipse

REPORT

anonymousId         796354bd-8f9e-4df7-b47c-487b0b02a75f
name                
email               
comment             
eclipseBuildId      4.7.1.M20170906-1700
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0_131-8u131-b11-2ubuntu1.16.04.3-b11
osgiWs              gtk
osgiOs              Linux
osgiOsVersion       4.4.0
osgiArch            x86_64
severity            UNKNOWN

STATUS

pluginId            org.eclipse.jdt.ui
pluginVersion       3.13.1.v20170822-1011
code                10001
severity            4
message             Internal Error
fingerprint         64b240de909bf083e7256cb2069802e9

Exception:java.lang.reflect.InvocationTargetException: null
	 at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:398)
	 at org.eclipse.jface.wizard.WizardDialog.run(WizardDialog.java:980)
	 at org.eclipse.jdt.internal.ui.wizards.NewElementWizard.performFinish(NewElementWizard.java:136)
	 at com.google.gdt.eclipse.suite.wizards.NewWebAppProjectWizard.performFinish(NewWebAppProjectWizard.java:115)
	 at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:778)
	 at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:417)
	 at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	 at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:81)
	 at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:249)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5268)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
	 at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	 at org.eclipse.jface.window.Window.open(Window.java:794)
	 at com.google.gdt.eclipse.core.actions.AbstractOpenWizardAction.run(AbstractOpenWizardAction.java:103)
	 at com.google.gdt.eclipse.suite.actions.NewWebAppToolbarHandler.execute(NewWebAppToolbarHandler.java:26)
	 at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:291)
	 at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	 at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	 at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	 at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	 at org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem.executeItem(HandledContributionItem.java:431)
	 at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:446)
	 at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5268)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
	 at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.dropdownEvent(AbstractContributionItem.java:422)
	 at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.handleWidgetSelection(AbstractContributionItem.java:433)
	 at org.eclipse.e4.ui.workbench.renderers.swt.AbstractContributionItem.lambda$2(AbstractContributionItem.java:472)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5268)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1348)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4522)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4107)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1150)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1039)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	 at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	 at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
Caused by: java.lang.NoSuchMethodError: org.eclipse.jdt.internal.core.JavaProject.computePackageFragmentRoots([Lorg/eclipse/jdt/core/IClasspathEntry;ZLjava/util/Map;)[Lorg/eclipse/jdt/core/IPackageFragmentRoot;
	 at com.google.gdt.eclipse.core.ClasspathUtilities.findRawClasspathEntryFor(ClasspathUtilities.java:163)
	 at com.google.gwt.eclipse.core.runtime.GwtSdk$ProjectBoundSdk.findGwtDevClasspathEntry(GwtSdk.java:361)
	 at com.google.gwt.eclipse.core.runtime.GwtSdk$ProjectBoundSdk.computeInstallPath(GwtSdk.java:266)
	 at com.google.gwt.eclipse.core.runtime.GwtSdk$ProjectBoundSdk.getInstallationPath(GwtSdk.java:189)
	 at com.google.gwt.eclipse.core.runtime.GwtSdk.findSdkFor(GwtSdk.java:411)
	 at com.google.gwt.eclipse.core.util.GwtVersionUtil.getProjectGwtVersion(GwtVersionUtil.java:63)
	 at com.google.gwt.eclipse.core.util.GwtVersionUtil.isGwtVersionGreaterOrEqualTo27(GwtVersionUtil.java:51)
	 at com.google.gdt.eclipse.suite.wizards.WebAppProjectCreator.createLaunchConfig(WebAppProjectCreator.java:555)
	 at com.google.gdt.eclipse.suite.wizards.WebAppProjectCreator.create(WebAppProjectCreator.java:372)
	 at com.google.gdt.eclipse.suite.wizards.NewWebAppProjectWizard.finishPage(NewWebAppProjectWizard.java:139)
	 at org.eclipse.jdt.internal.ui.wizards.NewElementWizard$2.run(NewElementWizard.java:120)
	 at org.eclipse.jdt.internal.core.BatchOperation.executeOperation(BatchOperation.java:39)
	 at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	 at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	 at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	 at org.eclipse.jdt.core.JavaCore.run(JavaCore.java:5660)
	 at org.eclipse.jdt.internal.ui.actions.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:105)
	 at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

```

**Updates** Next error is not related to GWT plugin.
~~Also, I'm getting errors in Problems view for existing projects after upgrading eclipse to 4.7.1.
For example:~~
```
Internal compiler error: java.lang.UnsupportedOperationException: no glb for [<T>, public class com.google.gwt.core.client.JavaScriptObject
	extends java.lang.Object
/*   methods   */
[unresolved] protected void <init>() 
[unresolved] private static native boolean callEquals(java.lang.Object, java.lang.Object) 
[unresolved] private static native int callHashCode(java.lang.Object) 
public final T cast() 
[unresolved] public static native com.google.gwt.core.client.JavaScriptObject createArray() 
[unresolved] public static native com.google.gwt.core.client.JavaScriptObject createArray(int) 
[unresolved] public static native com.google.gwt.core.client.JavaScriptObject createFunction() 
[unresolved] public static native com.google.gwt.core.client.JavaScriptObject createObject() 
[unresolved] public final boolean equals(java.lang.Object) 
[unresolved] private static native boolean hasEquals(java.lang.Object) 
[unresolved] private static native boolean hasHashCode(java.lang.Object) 
[unresolved] public final int hashCode() 
[unresolved] public native java.lang.String toSource() 
[unresolved] public final java.lang.String toString() 
[unresolved] private static native java.lang.String toStringSimple(com.google.gwt.core.client.JavaScriptObject) 
[unresolved] private static native java.lang.String toStringVerbose(com.google.gwt.core.client.JavaScriptObject) 


] extends java.lang.Object	SomeClass.java
```

**Comment by axls** [comment]
Updates. Last error (from Problems view) is not related to gwt plugin. It relates to changes in JDT type inference logic and can be workarounded.

**Comment by axls** [comment]
Closing after more deep investigation. This issue relates to Groovy Eclipse plugin (https://github.com/groovy/groovy-eclipse). Groovy plugin installs JDT patch wich contains latest JDT core not compatible with current GWT plugin. After uninstalling Groovy plugin the issue has gone.

**Comment by branflake2267** [comment]
Thanks for digging into this.
