### ISSUE TITLE
Getting internal jetty server TimeoutException when service call exeeds 30 seconds

### ISSUE THREAD

**Issue by swapnilpereira** [gwt-plugins/gwt-eclipse-plugin#378]
Caused by: java.util.concurrent.TimeoutException: Idle timeout expired: 30000/30000 ms
	at org.eclipse.jetty.io.IdleTimeout.checkIdleTimeout(IdleTimeout.java:161)
	at org.eclipse.jetty.io.IdleTimeout$1.run(IdleTimeout.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

**Comment by branflake2267** [comment]
I'm copying this from my response from the Sencha ticket. Could you try the workaround mentioned in the bug tracker? 

This looks like a bug in Jetty. I see a workaround in the bug.
https://github.com/eclipse/jetty.project/issues/235
https://bugs.eclipse.org/bugs/show_bug.cgi?id=478923 - Look for "around" and they mention set a longer timeout. It's possible that might help.
