### ISSUE TITLE
"Invalid thread access" errors when refreshing Gradle project

### ISSUE THREAD

**Issue by CrushaKRool** [gwt-plugins/gwt-eclipse-plugin#388]
Using the Gradle Buildship plugin and choosing "Refresh Gradle Project" from the context menu of a project in the Package Explorer, I encounter the errors below multiple times. Encountered it several times already, both in Eclipse Photon and the new "2018-09" release.

It begs of course the question whether the Buildship plugin is at fault here. However, since the GWT plugin is always the one to appear in the stacktrace, perhaps it is indeed the main offender.

Stacktraces:
```
!ENTRY org.eclipse.jface 4 2 2018-09-27 14:11:48.497
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Tree.setRedraw(Tree.java:4789)
	at org.eclipse.jface.viewers.AbstractTreeViewer.labelProviderChanged(AbstractTreeViewer.java:2203)
	at org.eclipse.jface.viewers.ContentViewer.handleLabelProviderChanged(ContentViewer.java:206)
	at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1207)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaOutlinePage$JavaOutlineViewer.handleLabelProviderChanged(JavaOutlinePage.java:464)
	at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:102)
	at org.eclipse.jface.viewers.BaseLabelProvider$1.run(BaseLabelProvider.java:75)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:47)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:176)
	at org.eclipse.jface.viewers.BaseLabelProvider.fireLabelProviderChanged(BaseLabelProvider.java:72)
	at org.eclipse.jface.viewers.DecoratingStyledCellLabelProvider.lambda$0(DecoratingStyledCellLabelProvider.java:78)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaUILabelProvider$1.run(JavaUILabelProvider.java:266)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaUILabelProvider.fireLabelProviderChanged(JavaUILabelProvider.java:263)
	at org.eclipse.jdt.internal.ui.viewsupport.AppearanceAwareLabelProvider.propertyChanged(AppearanceAwareLabelProvider.java:103)
	at org.eclipse.ui.internal.registry.EditorRegistry$2.run(EditorRegistry.java:342)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.registry.EditorRegistry.firePropertyChange(EditorRegistry.java:339)
	at org.eclipse.ui.internal.registry.EditorRegistry.setFileEditorMappings(EditorRegistry.java:1086)
	at org.sf.feeling.decompiler.SetupRunnable.updateClassDefaultEditor(SetupRunnable.java:326)
	at org.sf.feeling.decompiler.SetupRunnable$6.propertyChange(SetupRunnable.java:249)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:348)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:345)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.lambda$0(ScopedPreferenceStore.java:182)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:848)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:851)
	at org.eclipse.core.internal.preferences.EclipsePreferences.put(EclipsePreferences.java:863)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:636)
	at org.eclipse.ui.internal.registry.EditorRegistry.saveAssociations(EditorRegistry.java:1040)
	at com.google.gwt.eclipse.core.util.Util.resetDefaultEditor(Util.java:402)
	at com.google.gwt.eclipse.core.nature.GWTNature.resetDefaultEditors(GWTNature.java:91)
	at com.google.gwt.eclipse.core.nature.GWTNature.configure(GWTNature.java:100)
	at org.eclipse.core.internal.resources.NatureManager$1.run(NatureManager.java:147)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.resources.NatureManager.configureNature(NatureManager.java:163)
	at org.eclipse.core.internal.resources.NatureManager.configureNatures(NatureManager.java:209)
	at org.eclipse.core.internal.resources.Project.basicSetDescription(Project.java:106)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1269)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1296)
	at org.eclipse.buildship.core.workspace.internal.ProjectNatureUpdater.update(ProjectNatureUpdater.java:52)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenWorkspaceProject(SynchronizeGradleBuildOperation.java:217)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.addNewEclipseProjectToWorkspace(SynchronizeGradleBuildOperation.java:288)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeNonWorkspaceProject(SynchronizeGradleBuildOperation.java:270)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:179)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:134)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2314)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:131)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.eclipse.jdt.ui 4 2 2018-09-27 14:11:48.498
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ui".
!STACK 0
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4595)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:451)
	at org.eclipse.swt.widgets.Widget.checkWidget(Widget.java:369)
	at org.eclipse.swt.widgets.Tree.setRedraw(Tree.java:4789)
	at org.eclipse.jface.viewers.AbstractTreeViewer.labelProviderChanged(AbstractTreeViewer.java:2203)
	at org.eclipse.jface.viewers.ContentViewer.handleLabelProviderChanged(ContentViewer.java:206)
	at org.eclipse.jface.viewers.StructuredViewer.handleLabelProviderChanged(StructuredViewer.java:1207)
	at org.eclipse.jdt.internal.ui.javaeditor.JavaOutlinePage$JavaOutlineViewer.handleLabelProviderChanged(JavaOutlinePage.java:464)
	at org.eclipse.jface.viewers.ContentViewer$1.labelProviderChanged(ContentViewer.java:102)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaUILabelProvider$1.run(JavaUILabelProvider.java:266)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.internal.ui.viewsupport.JavaUILabelProvider.fireLabelProviderChanged(JavaUILabelProvider.java:263)
	at org.eclipse.jdt.internal.ui.viewsupport.AppearanceAwareLabelProvider.propertyChanged(AppearanceAwareLabelProvider.java:103)
	at org.eclipse.ui.internal.registry.EditorRegistry$2.run(EditorRegistry.java:342)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.internal.registry.EditorRegistry.firePropertyChange(EditorRegistry.java:339)
	at org.eclipse.ui.internal.registry.EditorRegistry.setFileEditorMappings(EditorRegistry.java:1086)
	at org.sf.feeling.decompiler.SetupRunnable.updateClassDefaultEditor(SetupRunnable.java:326)
	at org.sf.feeling.decompiler.SetupRunnable$6.propertyChange(SetupRunnable.java:249)
	at org.eclipse.ui.preferences.ScopedPreferenceStore$2.run(ScopedPreferenceStore.java:348)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.firePropertyChangeEvent(ScopedPreferenceStore.java:345)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.lambda$0(ScopedPreferenceStore.java:182)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:848)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:851)
	at org.eclipse.core.internal.preferences.EclipsePreferences.put(EclipsePreferences.java:863)
	at org.eclipse.ui.preferences.ScopedPreferenceStore.setValue(ScopedPreferenceStore.java:636)
	at org.eclipse.ui.internal.registry.EditorRegistry.saveAssociations(EditorRegistry.java:1040)
	at com.google.gwt.eclipse.core.util.Util.resetDefaultEditor(Util.java:402)
	at com.google.gwt.eclipse.core.nature.GWTNature.resetDefaultEditors(GWTNature.java:91)
	at com.google.gwt.eclipse.core.nature.GWTNature.configure(GWTNature.java:100)
	at org.eclipse.core.internal.resources.NatureManager$1.run(NatureManager.java:147)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.resources.NatureManager.configureNature(NatureManager.java:163)
	at org.eclipse.core.internal.resources.NatureManager.configureNatures(NatureManager.java:209)
	at org.eclipse.core.internal.resources.Project.basicSetDescription(Project.java:106)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1269)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1296)
	at org.eclipse.buildship.core.workspace.internal.ProjectNatureUpdater.update(ProjectNatureUpdater.java:52)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeOpenWorkspaceProject(SynchronizeGradleBuildOperation.java:217)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.addNewEclipseProjectToWorkspace(SynchronizeGradleBuildOperation.java:288)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeNonWorkspaceProject(SynchronizeGradleBuildOperation.java:270)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeGradleProjectWithWorkspaceProject(SynchronizeGradleBuildOperation.java:179)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.access$000(SynchronizeGradleBuildOperation.java:99)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation$1.run(SynchronizeGradleBuildOperation.java:134)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2292)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2314)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.synchronizeProjectsWithWorkspace(SynchronizeGradleBuildOperation.java:131)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildOperation.run(SynchronizeGradleBuildOperation.java:115)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.synchronizeBuild(SynchronizeGradleBuildsJob.java:85)
	at org.eclipse.buildship.core.workspace.internal.SynchronizeGradleBuildsJob.runToolingApiJob(SynchronizeGradleBuildsJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob$1.run(ToolingApiJob.java:73)
	at org.eclipse.buildship.core.util.progress.ToolingApiInvoker.invoke(ToolingApiInvoker.java:62)
	at org.eclipse.buildship.core.util.progress.ToolingApiJob.run(ToolingApiJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com.gwtplugins.gwt.eclipse.core 1 0 2018-09-27 14:11:48.504
!MESSAGE Reset default editor for extension: xml
```

**Comment by protoism** [comment]
This ticket is really old, and problem is very likely related to buildship.
@CrushaKRool do you think that this ticket is still relevant with never versions (or, better, upcoming version?)

**Comment by CrushaKRool** [comment]
I could not find such stacktraces anymore in a current Eclipse version with a more recent version of this plugin. So maybe it resolved itself by now.
