### ISSUE TITLE
Support GWT 2.10.0

### ISSUE THREAD

**Issue by foal** [gwt-plugins/gwt-eclipse-plugin#403]
GWT 2.10.0 is out. Please support it. Right now, I see the following error
```  
java.lang.NullPointerException: Cannot invoke "com.google.gwt.eclipse.core.runtime.GwtSdk.usesGwtDevProject()" because "sdk" is null
	at com.google.gwt.eclipse.core.launch.GWTLaunchConfiguration.maybeGetDevJarPath(GWTLaunchConfiguration.java:176)
	at com.google.gwt.eclipse.core.launch.GWTLaunchConfiguration.computeDynamicVMArgs(GWTLaunchConfiguration.java:120)
	at com.google.gwt.eclipse.core.launch.GWTLaunchConfiguration.computeCompileDynamicVMArgsAsList(GWTLaunchConfiguration.java:41)
	at com.google.gwt.eclipse.core.compile.GWTCompileRunner.computeCompilerCommandLine(GWTCompileRunner.java:223)
	at com.google.gwt.eclipse.core.compile.GWTCompileRunner.compile(GWTCompileRunner.java:81)
	at com.google.gwt.eclipse.core.compile.GWTCompileRunner.compileWithCancellationSupport(GWTCompileRunner.java:126)
	at com.google.gwt.eclipse.core.actions.GWTCompileToolbarHandler$1.runInWorkspace(GWTCompileToolbarHandler.java:136)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by foal** [comment]
BTW - https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/404#issuecomment-1170792264
