### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by vladikk007** [gwt-plugins/gwt-eclipse-plugin#408]
Could you please add Java 17 support? 
Now, after installing plugin from Marketplace, no GWT icons are displayed in Eclipse. 
Error log shows:
```
org.osgi.framework.BundleException: Could not resolve module: com.gwtplugins.gdt.eclipse.core [1004]
  Unresolved requirement: Require-Bundle: com.gwtplugins.gdt.eclipse.platform
    -> Bundle-SymbolicName: com.gwtplugins.gdt.eclipse.platform; bundle-version="3.0.0.201710131939"; singleton:="true"
       com.gwtplugins.gdt.eclipse.platform [1006]
         No resolution report for the bundle.  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource com.gwtplugins.gdt.eclipse.platform [osgi.identity; type="osgi.bundle"; version:Version="3.0.0.201710131939"; osgi.identity="com.gwtplugins.gdt.eclipse.platform"; singleton:="true"] because it is exposed to package 'javax.servlet' from resources javax.servlet [osgi.identity; type="osgi.bundle"; version:Version="3.0.0.v201112011016"; osgi.identity="javax.servlet"] and jakarta.servlet-api [osgi.identity; type="osgi.bundle"; version:Version="4.0.0"; osgi.identity="jakarta.servlet-api"] via two dependency chains.

Chain 1:
  com.gwtplugins.gdt.eclipse.platform [osgi.identity; type="osgi.bundle"; version:Version="3.0.0.201710131939"; osgi.identity="com.gwtplugins.gdt.eclipse.platform"; singleton:="true"]
    require: (osgi.wiring.bundle=javax.servlet)
     |
    provide: osgi.wiring.bundle: javax.servlet
  javax.servlet [osgi.identity; type="osgi.bundle"; version:Version="3.0.0.v201112011016"; osgi.identity="javax.servlet"]

Chain 2:
  com.gwtplugins.gdt.eclipse.platform [osgi.identity; type="osgi.bundle"; version:Version="3.0.0.201710131939"; osgi.identity="com.gwtplugins.gdt.eclipse.platform"; singleton:="true"]
    import: (osgi.wiring.package=org.mortbay.util.ajax)
     |
    export: osgi.wiring.package=org.mortbay.util.ajax; uses:=javax.servlet
  org.mortbay.jetty.util [osgi.identity; type="osgi.bundle"; version:Version="6.1.26"; osgi.identity="org.mortbay.jetty.util"]
    import: (osgi.wiring.package=javax.servlet)
     |
    export: osgi.wiring.package: javax.servlet
  jakarta.servlet-api [osgi.identity; type="osgi.bundle"; version:Version="4.0.0"; osgi.identity="jakarta.servlet-api"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.lambda$1(ModuleContainer.java:1834)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1829)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1775)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1739)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:228)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:339)
```

on Eclipse 4.22.0

**Comment by keinhaar** [comment]
This is not a problem with JAVA 17, but instead a problem in the plugin itself.

It can be manually fixed by editing the jar file for **_com.gwtplugins.gdt.eclipse.platform_**. To do so, open the **_META_INF/MANIFEST.MF_** that's inside the jar, and remove the **javax.servlet,** entry from **Require-Bundle**. Update the jar with the new MANIFEST.MF, and it will start on Eclipse 2021-12.

Or you can use my own, fixed Version from here: https://github.com/keinhaar/gwt-eclipse-plugin/releases, but that requires an installation of eclipse where you never installed the plugin. It will install just fine in a fresh installation of eclipse-2021-12.

**Comment by protoism** [comment]
This issue is probably fixed by https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/428 (already merged)
You may try
   https://eclipse.gwtproject.org.vertispan.com/2023-01-18/
which will soon be supersed by an official 4.0.0 release
