### ISSUE TITLE
Long paths stopped working on 4.0.0

### ISSUE THREAD

**Issue by eliasbalasis** [gwt-plugins/gwt-eclipse-plugin#468]
It is great that we are now having an entry in Eclipse Marketplace for GWT Eclipse plugin 4.0.0

Please accept my sincere congratulations to all the contributors.

Unfortunately, some historical behavior seems to have changed.

Long paths under Windows OS are not working anymore.

I am getting the following from Super Development Mode launcher:

Exception occurred executing command line.
Cannot run program "<path_to_java_bin_84_chars_long>\javaw.exe" (in directory "<long_path_to_GWT_maven_module_target_folder_356_chars_long>"): CreateProcess error=267, The directory name is invalid

The underlying exception is the following, captured from Eclipse Error Log:
`java.io.IOException: Cannot run program "<path_to_java_bin_84_chars_long>\javaw.exe" (in directory "<long_path_to_GWT_maven_module_target_folder_356_chars_long>"): CreateProcess error=267, The directory name is invalid`
`	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)`
`	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)`
`	at java.base/java.lang.Runtime.exec(Runtime.java:594)`
`	at org.eclipse.debug.core.DebugPlugin.exec(DebugPlugin.java:970)`
`	at org.eclipse.jdt.launching.AbstractVMRunner.exec(AbstractVMRunner.java:116)`
`	at org.eclipse.jdt.internal.launching.StandardVMRunner.run(StandardVMRunner.java:526)`
`	at org.eclipse.jdt.launching.JavaLaunchDelegate.launch(JavaLaunchDelegate.java:176)`
`	at com.google.gdt.eclipse.suite.launch.WebAppLaunchDelegate.launch(WebAppLaunchDelegate.java:151)`
`	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:806)`
`	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:717)`
`	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1040)`
`	at org.eclipse.debug.internal.ui.DebugUIPlugin$1.run(DebugUIPlugin.java:1243)`
`	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)`
`Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid`
`	at java.base/java.lang.ProcessImpl.create(Native Method)`
`	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)`
`	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)`
`	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)`
`	... 12 more`

I am running Eclipse 2023-03 with GWT Plugin 4.0.0

This is running successfully with Eclipse 2021-03,  GWT Plugin 3 and the same long paths

**Comment by eliasbalasis** [comment]
I am finding suspicious that <path_to_java_bin_84_chars_long> points to a Java8 distribution, as I am running the SuperDevMode launcher using Java8 and my GWT Maven module has JavaSE-1.8 execution environment with same JRE as the running one attached, but the ProcessBuilder comes from somewhere else as it has a java.base prefix which does not exist on Java8.

**Comment by eliasbalasis** [comment]
In my maven POM,
I tried to override <webappDirectory> and <hostedWebapp>
with something smaller in order to produce a shorter path, but the plugin doesn't seem to be honoring these parameters.

**Comment by eliasbalasis** [comment]
This is finally a false alarm.
