### ISSUE TITLE
CloudEndpointsBuilder npe in Cloud Tools

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#62]
NPE shows up on Ubuntu. 

```
java.lang.NullPointerException
	at com.google.gwt.eclipse.wtp.GwtWtpPlugin.possiblyTerminateLaunchConfiguration(GwtWtpPlugin.java:346)
	at com.google.gwt.eclipse.wtp.GwtWtpPlugin.processLauncherEvent(GwtWtpPlugin.java:179)
	at com.google.gwt.eclipse.wtp.GwtWtpPlugin.processProcessorEvents(GwtWtpPlugin.java:139)
	at com.google.gwt.eclipse.wtp.GwtWtpPlugin$1.handleDebugEvents(GwtWtpPlugin.java:129)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.run(DebugPlugin.java:1151)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.debug.core.DebugPlugin$EventNotifier.dispatch(DebugPlugin.java:1187)
	at org.eclipse.debug.core.DebugPlugin$EventDispatchJob.run(DebugPlugin.java:431)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by branflake2267** [comment]
```
Errors occurred during the build.
Errors running builder 'Google App Engine Cloud Endpoints Builder for WTP' on project 'contactmgr'.
```

```
Java Model Exception: Java Model Status [target/classes/ca/defuse [in contactmgr] is not on its project's build path]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:566)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:247)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:505)
	at org.eclipse.jdt.internal.core.CompilationUnit.openAncestors(CompilationUnit.java:1173)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:241)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:579)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:316)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:302)
	at org.eclipse.jdt.internal.core.JavaElement.getChildren(JavaElement.java:257)
	at org.eclipse.jdt.internal.core.JavaElement.getChildrenOfType(JavaElement.java:271)
	at org.eclipse.jdt.internal.core.CompilationUnit.getTypes(CompilationUnit.java:920)
	at com.google.gdt.eclipse.appengine.swarm.util.SwarmAnnotationUtils.collectApiTypes(SwarmAnnotationUtils.java:40)
	at com.google.appengine.eclipse.wtp.swarm.CloudEndpointsBuilder$1.visit(CloudEndpointsBuilder.java:120)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:69)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:80)
	at org.eclipse.core.internal.events.ResourceDelta.accept(ResourceDelta.java:49)
	at com.google.appengine.eclipse.wtp.swarm.CloudEndpointsBuilder.apiClassesChanged(CloudEndpointsBuilder.java:108)
	at com.google.appengine.eclipse.wtp.swarm.CloudEndpointsBuilder.build(CloudEndpointsBuilder.java:71)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:734)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:206)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:246)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:302)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:358)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:381)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:143)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:241)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

```

**Comment by branflake2267** [comment]
Also server working directory is different. 

![screen shot 2015-05-13 at 9 49 01 pm](https://cloud.githubusercontent.com/assets/1326504/7626215/efdccc90-f9b9-11e4-9f5c-d5c9a8e494cd.png)

**Comment by branflake2267** [comment]
It appears the launcherDir is the problem for the code server b/c it can't derive the correct directory based on the Server configuration. 

Solution, if `other` is used, then the path needs to move from the flag to the setting.

**Comment by branflake2267** [comment]
This will shift to Google's Plugin.
