### ISSUE TITLE
JPA facet detection error

### ISSUE THREAD

**Issue by branflake2267** [gwt-plugins/gwt-eclipse-plugin#75]
JPA facet detection is not configuring version. There is an exception b/c the provided library does not have a platform set. Once it's set it helps. 

Platform set below
![screen shot 2015-05-24 at 7 33 56 pm](https://cloud.githubusercontent.com/assets/1326504/7790986/e6e8743c-024b-11e5-8485-f1a769a9843a.png)

**Comment by branflake2267** [comment]
Adding error:
```
The following data will be sent:

------
STATUS
------
pluginId            org.eclipse.jst.common.project.facet.core
pluginVersion       1.4.400.v201403261418
code                -1
severity            4
message             The variable jpaPlatform is not defined
fingerprint         c8d3187e

Exception:org.eclipse.core.runtime.CoreException: The variable jpaPlatform is not defined
	 at org.eclipse.core.internal.expressions.WithExpression.evaluate(WithExpression.java:68)
	 at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
	 at org.eclipse.core.internal.expressions.AndExpression.evaluate(AndExpression.java:31)
	 at org.eclipse.core.internal.expressions.CompositeExpression.evaluateAnd(CompositeExpression.java:53)
	 at org.eclipse.core.internal.expressions.EnablementExpression.evaluate(EnablementExpression.java:55)
	 at org.eclipse.jst.common.project.facet.core.libprov.internal.LibraryProvider.isEnabledFor(LibraryProvider.java:287)
	 at org.eclipse.jst.common.project.facet.core.libprov.LibraryInstallDelegate.refresh(LibraryInstallDelegate.java:364)
	 at org.eclipse.jst.common.project.facet.core.libprov.LibraryInstallDelegate.reset(LibraryInstallDelegate.java:450)
	 at org.eclipse.jst.common.project.facet.core.libprov.LibraryInstallDelegate.<init>(LibraryInstallDelegate.java:138)
	 at org.eclipse.jst.common.project.facet.core.libprov.LibraryInstallDelegate.<init>(LibraryInstallDelegate.java:151)
	 at org.eclipse.m2e.wtp.jpa.internal.configurators.JpaProjectConfigurator.getNoOpLibraryProvider(JpaProjectConfigurator.java:233)
	 at org.eclipse.m2e.wtp.jpa.internal.configurators.JpaProjectConfigurator.getDataModel(JpaProjectConfigurator.java:191)
	 at org.eclipse.m2e.wtp.jpa.internal.configurators.JpaProjectConfigurator.configureFacets(JpaProjectConfigurator.java:145)
	 at org.eclipse.m2e.wtp.jpa.internal.configurators.JpaProjectConfigurator.configure(JpaProjectConfigurator.java:108)
	 at org.eclipse.m2e.core.project.configurator.AbstractLifecycleMapping.configure(AbstractLifecycleMapping.java:120)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:501)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$3.call(ProjectConfigurationManager.java:1)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:494)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:432)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:345)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager$2.call(ProjectConfigurationManager.java:1)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
	 at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
	 at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
	 at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:342)
	 at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:77)
	 at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	 at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

------
STATUS
------
pluginId            org.eclipse.core.expressions
pluginVersion       3.5.0.v20150421-2214
code                301
severity            4
message             The variable jpaPlatform is not defined [detached from CoreException of Status 'The variable jpaPlatform is not defined' by Error Reporting]
fingerprint         00000000


------
REPORT
------
anonymousId         7689a93d-d258-431c-b536-d31ae368c2c5
name                Brandon Donnelson
email               branflake2267@gmail.com
comment             
eclipseBuildId      4.5.1.M20150904-0015
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0-ea-b123
osgiWs              cocoa
osgiOs              MacOSX
osgiOsVersion       10.11.2
osgiArch            x86_64
logMessage          false
ignoreSimilar       false

-------
BUNDLES
-------
name                org.eclipse.core.expressions
version             3.5.0.v20150421-2214

name                org.eclipse.core.jobs
version             3.7.0.v20150330-2103

name                org.eclipse.core.resources
version             3.10.1.v20150725-1910

name                org.eclipse.jst.common.project.facet.core
version             1.4.400.v201403261418

name                org.eclipse.m2e.core
version             1.6.2.20150902-0002

name                org.eclipse.m2e.core.ui
version             1.6.2.20150902-0002

name                org.eclipse.m2e.wtp.jpa
version             1.2.1.20150819-2224

name                org.eclipse.m2e.wtp
version             1.2.1.20150819-2220


```

**Comment by branflake2267** [comment]
https://github.com/gwt-plugins/gwt-eclipse-plugin/pull/120/files
