### ISSUE TITLE
AppEngine: sdk is null for *project*

### ISSUE THREAD

**Issue by dodgex** [gwt-plugins/gwt-eclipse-plugin#85]
Hey there,

i just updated this plugin and while searching for some options in project properties i opened the `Google Classic > AppEnigne` page.

While opening it i got the following message in eclipse error log:
`sdk is null for *project*` + a long list of packages of all my source folder and dependencies
no stacktrace available.

when hitting ok i get another error with the message: `Unexpected Exception`
and the following stacktrace
```
java.lang.NullPointerException
	at com.google.appengine.eclipse.core.properties.ui.GaeProjectPropertyPage.saveChangesToAppEngineWebXml(GaeProjectPropertyPage.java:904)
	at com.google.appengine.eclipse.core.properties.ui.GaeProjectPropertyPage.saveProjectProperties(GaeProjectPropertyPage.java:336)
	at com.google.gdt.eclipse.core.ui.AbstractProjectPropertyPage.performOk(AbstractProjectPropertyPage.java:77)
	at org.eclipse.jface.preference.PreferenceDialog$12.run(PreferenceDialog.java:992)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
	at org.eclipse.jface.preference.PreferenceDialog.okPressed(PreferenceDialog.java:971)
	at org.eclipse.ui.internal.dialogs.FilteredPreferenceDialog.okPressed(FilteredPreferenceDialog.java:460)
	at org.eclipse.jface.preference.PreferenceDialog.buttonPressed(PreferenceDialog.java:236)
	at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:619)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:248)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:832)
	at org.eclipse.jface.window.Window.open(Window.java:808)
	at org.eclipse.ui.dialogs.PropertyDialogAction.run(PropertyDialogAction.java:160)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:519)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:595)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:511)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:420)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1061)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4172)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3761)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
```

I'm not using AppEngine at all in my project.

**Comment by branflake2267** [comment]
Thanks for reporting.

**Comment by jonl-percsolutions-com** [comment]
I am also seeing this exception when attempting to remove GAE SDK from from a project with existing appengine sdk settings.

**Comment by jonl-percsolutions-com** [comment]
Seems to be an issue with the assumption in GaePropertyPropertyPage.saveChangesToAppEngineWebXml that the GaeProject object returned is not null, which might not be the case when upgrading from the old eclipse plugin or if removing GAE from the project and there was never a GaeNature associated.  So saveChangesToAppEnginWebXml appears to sometimes be called at the wrong time, when these edge cases exist.

```
GaePropertyPropertyPage
 private void saveChangesToAppEngineWebXml() throws IOException, CoreException {
    GaeProject gaeProject = GaeProject.create(getProject());
    if (appId == null) {
      appId = "ChangeMe";
    }
    if (!appId.equals(initialAppId)) {
      gaeProject.setAppId(appId, true);
    }

    if (!version.equals(initialVersion)) {
      gaeProject.setAppVersion(version, true);
    }
  }


GaeProject
  public static GaeProject create(IProject project) {
    assert project != null;
    if (GaeNature.isGaeProject(project)) {
      return new GaeProject(JavaCore.create(project));
    }
    return null;
  }

GaeNature
  public static boolean isGaeProject(IProject project) {
    try {
      return project.isAccessible() && project.hasNature(GaeNature.NATURE_ID);
    } catch (CoreException e) {
      AppEngineCorePluginLog.logError(e);
    }
    return false;
  }
```

**Comment by branflake2267** [comment]
Good to know, thanks for the details. Could you tell me what type of project you have, standard java, maven or other?

**Comment by jonl-percsolutions-com** [comment]
It is a standard GWT Project that has been converted from a GAE project, but was initially created under the old eclipse Google plugin.

**Comment by branflake2267** [comment]
I've added an NPE guard. The fix will go out in the next deploy, but I'll wait till I get a couple more things in first.
